export const previewStyles = [
    {
        gridBackgroundColor: 'white',
        rootBackgroundColor: '#FAFAFA',
        itineraryTitleColor: '#BA886E',
        itineraryTitleFontFamily: 'Gallient Regular',
        itinerarySubTitleColor: '#BA886E',
        itinerarySubTitleFontFamily: 'MADE Mirage Regular',
        itineraryBookingDateColor: '#BA886E',
        itineraryBookingDateFontFamily: 'Cormorant Garamond',
        abstractRootBackgroundColor: '#FAFAFA',
        abstractTitleColor: '#BA886E',
        abstractTextColor: '#242424',
        abstractTitleFontFamily: 'Cormorant',
        FlightDivBackgroundColor: '#FAFAFA',
        FlightCardTitleColor: '#BA886E',  
        FlightCardNoteColor: '#242424',
        hotelcardRoot1BackgroundColor: 'linear-gradient(180deg, rgba(225,221,216,1) 0%, rgba(225,221,216,1) 100%, rgba(255,255,255,1) 100%, rgba(255,255,255,1) 100%)',
        hotelcardRoot2BackgroundColor: 'linear-gradient(180deg, rgba(225,221,216,1) 0%, rgba(225,221,216,1) 90%, rgba(255,255,255,1) 90%, rgba(255,255,255,1) 100%)',
        hotelcardRoot2MediaBackgroundColor: 'rgba(225,221,216,1)',
        hotelcardTitleColor: '#242424',
        hotelcardTitleFontFamily: 'MADE Mirage Regular',
        hotelcardDescriptionColor: '#242424',
        cruisecardTitleColor: '#FFF',
        cruisecardTitleFontFamily: 'Cormorant',
        cruisecardDescriptionColor: '#FFF',
        cruisecardRoot1BackgroundColor: '#25303F',
        transportcardTitleColor: '#333333',
        transportcardTitleFontFamily: 'Cormorant',
        transportcardDescriptionColor: '#BA886E',
        transportcardRoot1BackgroundColor: '#25303F',
        activitycardTitleColor: '#242424',
        activitycardTitleFontFamily: 'Cormorant',
        checkDateColor: '#BA886E'        
    },
    {
        gridBackgroundColor: 'white',
        rootBackgroundColor: '#FAFAFA',
        itineraryTitleColor: '#242424',
        itineraryTitleFontFamily: 'Montserrat',
        itinerarySubTitleColor: '#242424',
        itinerarySubTitleFontFamily: 'Roboto',
        itineraryBookingDateColor: '#242424',
        itineraryBookingDateFontFamily: 'Montserrat',
        abstractRootBackgroundColor: '#FAFAFA',
        abstractTitleColor: '#BA886E',
        abstractTextColor: '#242424',
        abstractTitleFontFamily: 'Montserrat',
        FlightDivBackgroundColor: '#FAFAFA',
        FlightCardTitleColor: '#BA886E', 
        FlightCardNoteColor: '#242424',
        hotelcardRoot1BackgroundColor: '#ECECEC',
        hotelcardRoot2BackgroundColor: '#ECECEC',
        hotelcardRoot2MediaBackgroundColor: '#ECECEC',
        hotelcardTitleColor: '#242424',
        hotelcardTitleFontFamily: 'Montserrat',
        hotelcardDescriptionColor: '#242424',
        cruisecardTitleColor: '#FFF',
        cruisecardTitleFontFamily: 'Montserrat',
        cruisecardDescriptionColor: '#242424',
        cruisecardRoot1BackgroundColor: '#242424',
        transportcardTitleColor: '#333333',
        transportcardTitleFontFamily: 'Montserrat',
        transportcardDescriptionColor: '#000000',
        transportcardRoot1BackgroundColor: '#25303F',
        activitycardTitleColor: '#242424',
        activitycardTitleFontFamily: 'Montserrat',
        checkDateColor: '#828282'
    },
    {
        gridBackgroundColor: '#E5E5E5',
        rootBackgroundColor: 'linear-gradient(180deg, #FBF8F3 0%, rgba(255, 255, 255, 0) 100%)',
        itineraryTitleColor: '#84897C',
        itineraryTitleFontFamily: 'Cormorant Garamond',
        itinerarySubTitleColor: '#242424',
        itinerarySubTitleFontFamily: 'Raleway',
        itineraryBookingDateColor: '#84897C',
        itineraryBookingDateFontFamily: 'Cormorant Garamond',
        abstractRootBackgroundColor: 'rgba(250, 250, 250, 0.4)',
        abstractTitleColor: '#84897C',
        abstractTextColor: '#242424',
        abstractTitleFontFamily: 'Cormorant Garamond',
        FlightDivBackgroundColor: 'rgba(250, 250, 250, 0.3)',
        FlightCardTitleColor: '#84897C', 
        FlightCardNoteColor: '#242424',
        hotelcardRoot1BackgroundColor: 'rgba(132, 137, 124, 0.2)',
        hotelcardRoot2BackgroundColor: 'rgba(132, 137, 124, 0.2)',
        hotelcardRoot2MediaBackgroundColor: 'rgba(132, 137, 124, 0.2)',
        hotelcardTitleColor: '#84897C',  
        hotelcardTitleFontFamily: 'Cormorant Garamond',
        hotelcardDescriptionColor: '#242424',
        cruisecardTitleColor: '#FFF',
        cruisecardTitleFontFamily: 'Cormorant Garamond',
        cruisecardDescriptionColor: '#242424',
        cruisecardRoot1BackgroundColor: '#84897C',
        transportcardTitleColor: '#333333',
        transportcardTitleFontFamily: 'Cormorant',
        transportcardDescriptionColor: '#000000',
        transportcardRoot1BackgroundColor: '#25303F',
        activitycardTitleColor: '#242424',
        activitycardTitleFontFamily: 'Cormorant',
        checkDateColor: '#84897C'
    },
    {
        gridBackgroundColor: '#25303F',
        rootBackgroundColor: '#25303F',
        itineraryTitleColor: '#C9A96A',
        itineraryTitleFontFamily: 'Cormorant Garamond',
        itinerarySubTitleColor: '#FFF',
        itinerarySubTitleFontFamily: 'Raleway',
        itineraryBookingDateColor: '#C9A96A',
        itineraryBookingDateFontFamily: 'Cormorant Garamond',
        abstractRootBackgroundColor: 'rgba(250, 250, 250, 0.1)',
        abstractTitleColor: '#C9A96A',
        abstractTextColor: '#FFF',
        abstractTitleFontFamily: 'Cormorant Garamond',
        FlightDivBackgroundColor: 'rgba(250, 250, 250, 0.1)',
        FlightCardTitleColor: '#FFFFFF',     
        FlightCardNoteColor: '#FFFFFF',
        hotelcardRoot1BackgroundColor: 'rgba(132, 137, 124, 0.2)',
        hotelcardRoot2BackgroundColor: 'rgba(132, 137, 124, 0.2)',
        hotelcardRoot2MediaBackgroundColor: 'rgba(132, 137, 124, 0.2)',
        hotelcardTitleColor: '#C9A96A',
        hotelcardTitleFontFamily: 'Cormorant Garamond',
        hotelcardDescriptionColor: '#FFF',
        cruisecardTitleColor: '#FFF',
        cruisecardTitleFontFamily: 'Cormorant Garamond',
        cruisecardDescriptionColor: '#242424',
        cruisecardRoot1BackgroundColor: '#84897C',
        transportcardTitleColor: '#C9A96A',
        transportcardTitleFontFamily: 'Cormorant',
        transportcardDescriptionColor: '#000000',
        transportcardRoot1BackgroundColor: '#25303F',
        activitycardTitleColor: '#242424',
        activitycardTitleFontFamily: 'Cormorant',
        checkDateColor: '#C9A96A'
    }

]