# This is a basic workflow to help you get started with Actions
# https://github.com/matheusvanzan/sshpass-action
# https://github.com/marketplace/actions/sshpass-github-action

name: LUCIA-LIVE-AUTO-DEPLOY

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

# Disabling build for now
# build:
#
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
##         node-version: [12.x, 14.x, 16.x]
#        node-version: [16.x]
#        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v2
#      with:
#        node-version: ${{ matrix.node-version }}
#        cache: 'npm'
#    - run: npm ci
#     - run: npm run build --if-present
#    - run: npm test

# Begin deploy if build succeeds
 deploy:
    # Don't run if build fail
#    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Your SSH step
    - name: Run sshpass commands
      uses: eaproc/sshpass-action@v2
      with:
        host: ${{ secrets.LUCIA_LIVE_HOST }}
        user: ${{ secrets.LUCIA_LIVE_HOST_USER }}
        pass: ${{ secrets.LUCIA_LIVE_HOST_PASS }}
        run: |
          echo "Entering directory"
          ./update-lucia-app-complete.sh
          echo "DONE UPDATING! LUCIA Should be live now"
